#!/bin/bash
#####################################################
#
#	alphafold_monitor
#	-checks if the docker is running
#	-sends you an email once the docker is done
#	v1.0 : JuanCastillo 2021_24_11
################################################### 

DOCKERUSERLOG="/data_sbgamma/alphafold/"`whoami`".log"
LASTDOCKER="tango"
LASTLOCATION="zulu"
LINENUMBER="0"
RUNNING="true"

function print_doing_nothing(){
	### message repeated
	echo 
	echo "	Doing nothing: Bye...";
	echo
}

function findlastdocker(){
	LASTDOCKER=`tail -1 $DOCKERUSERLOG | awk -F"," '{print $1}'`
	LASTLOCATION=`tail -1 $DOCKERUSERLOG | awk -F"," '{print $5}'`
	LINENUMBER=`grep -n $LASTDOCKER $DOCKERUSERLOG | cut -f1 -d:`
}

function error_wrong_host(){
	tput setaf 1;
	echo
	echo	"	[ERROR] The logged docker doesn't run here: cannot monitor"
	echo 	"	exiting..."
	echo
	tput sgr0;
}

function is_docker_running(){
	### runs in the background, checks if docker is done
	echo
	echo "	Activating monitoring... run log on: " $LASTDOCKER"_status.log"
	echo "	You will get an email when the docker is done"
	while $RUNNING; do
		sleep 60
		containers=$(docker ps | awk '{if(NR>1) print $NF}')  		# get all running docker container names
		#for container in $containers
		#do
		if [[ "$containers" =~ "$LASTDOCKER" ]]; then
			RUNNING="true"
			status=`docker ps -f name=$LASTDOCKER --format '{{.Status}}'`
			echo "	docker $LASTDOCKER status: " $status >> $LASTDOCKER"_status.log"
		else
			RUNNING="false"
			message="[DONE] Docker $LASTDOCKER on $LASTLOCATION  done, last status : $status"
			#echo $message
			echo $message | mail -s "Docker $LASTDOCKER is done" "`whoami`@biophys.mpg.de"
			sed -i "${LINENUMBER}s/NOT/${status}/" $DOCKERUSERLOG
		fi
		#done	
	done &
}

############### main script #######################

status="done"

if [[ $# -eq 0 ]] ; then

	tput setaf 2;
 	echo 
	echo "	Starting monitor"
	echo
	tput sgr0;
	read -p "	Continue (y/n)?" CONT
	if [ "$CONT" = "y" ]; then
		# get name of last running docker
		findlastdocker
		#echo "	last docker on log : " $LASTDOCKER   " running on : " $LASTLOCATION " line: " $LINENUMBER
		echo "	last docker on log : " $LASTDOCKER   " running on : " $LASTLOCATION 
		tput setaf 2;
		read -p "	Continue (y/n)?" CONT2
		tput sgr0;
		if [ "$CONT2" = "y" ]; then
			if [[ $LASTLOCATION == `hostname` ]]; then
				is_docker_running
			else
				error_wrong_host
				exit 1
			fi
		else
			tput setaf 2;
			read -p "	Name docker manually (y/n)?" CONT3
			tput sgr0;
			if [ "$CONT3" = "y" ]; then
				read -p "	Please introduce the name of the docker to monitor: " LASTDOCKER
				is_docker_running
			else
				print_doing_nothing
			fi
		fi	
	else
		print_doing_nothing
	fi
fi


